### ISSUE TITLE
Error calling String value method on nil

### ISSUE THREAD

**Issue by mgood** [kylelemons/godebug#13]
We were trying to use the `PrintStringers` option (it looks like `PrintTextMarshalers` would have the same issue), but we have some structs that include pointers to types with a `String()` method with a value receiver. `time.Weekday` provides a simple example where it detects that `*time.Weekday` implements `Stringer` and tries to call it with a nil pointer:

```go
cfg := pretty.Config{
	PrintStringers: true,
}
cfg.Sprint(struct {
	Day *time.Weekday
}{
	Day: nil,
})
```

```
panic: value method time.Weekday.String called using nil *Weekday pointer

time.(*Weekday).String()
	<autogenerated>:45 +0xc1
github.com/kylelemons/godebug/pretty.(*Config).val2node()
	src/github.com/kylelemons/godebug/pretty/reflect.go:48 +0x1a6a
github.com/kylelemons/godebug/pretty.(*Config).val2node()
	src/github.com/kylelemons/godebug/pretty/reflect.go:95 +0xfa9
github.com/kylelemons/godebug/pretty.(*Config).fprint()
	src/github.com/kylelemons/godebug/pretty/public.go:98 +0x94
github.com/kylelemons/godebug/pretty.(*Config).Sprint()
	src/github.com/kylelemons/godebug/pretty/public.go:120 +0x6c
```

I may look into this a bit more, but wanted to go ahead and open an issue for it.

**Comment by kylelemons** [comment]
This is fixed in `github.com/kylelemons/godebug@master` if you're using modules -- let me know if this resolves the issue for you, and I'll cut a new module release.
