### ISSUE TITLE
Compare() function uses a lot of RAM

### ISSUE THREAD

**Issue by KernelDeimos** [kylelemons/godebug#15]
Because compare first converts the inputs to strings and then uses a diff library, it uses an absolutely enormous amount of ram, making it unusable for some intense purposes.

I'm probably going to have to write my own such Compare function for my purposes 'cause I can't find one, so if I do that I'll definitely submit a PR.

**Comment by kylelemons** [comment]
Yeah, unfortuantely the algorithm used by `pretty` to stringify types only happens to be useful for comparisons, it was not really designed with that in mind, particularly for large structures.

I personally recommend [`github.com/google/go-cmp/cmp`](https://godoc.org/github.com/google/go-cmp/cmp) for diffing structures in unit tests.  It was designed with this use-case in mind, and will probably do a lot better performance-wise.
