### ISSUE TITLE
Inifinite recursion issues.

### ISSUE THREAD

**Issue by crunk1** [kylelemons/godebug#16]
I have some data structures with lots of pointers, back pointers, and the like. Due to all these pointers, there are cycles. Would it be reasonable to cache pointers and check that Print/Sprint/etc don't visit the same pointer twice?

**Comment by crunk1** [comment]
Unless I'm wrong, your pretty prints don't include pointer values. My idea for truncating problematic recursive cycles would probably need pointer values to be printed. Thus, when truncating a value, something as follows could be used:

{Some: "field",
 Another: "field",
 PointerToSomethingElse: <sometype at 0x...> {
  ...
 },
 RecursivePointer: <truncated sometype at 0x...>
}

**Comment by kylelemons** [comment]
If you can, take a look at the PR #18 and see if that works for you.

**Comment by crunk1** [comment]
lgtm, are you wanting an lgtm on the PR?

**Comment by kylelemons** [comment]
Still trying to figure out the exact details.  See the PRs for commentary; I think we're close, though I'm about to disappear for a few days so it may not be until this weekend before it makes it in.  Thanks for taking a look!

**Comment by kylelemons** [comment]
The latest release v1.1.0 now includes support for self-referential structures, though it is not enabled by default because of the performance differences.
