### ISSUE TITLE
Configuration for pretty.Compare

### ISSUE THREAD

**Issue by shnsk** [kylelemons/godebug#2]
It would be nice if we can pass configurations to Compare, namely PrintStringers.

What I have in mind to have Compare method added to Config, so that
we can do something like the following:

config := &pretty.Config {
  PrintStringers: true,
}
cmp := config.Compare(got, want)

Thanks!

**Comment by cryptix** [comment]
+1

I'd like to be able to only diff exported fields.

**Comment by kylelemons** [comment]
https://godoc.org/github.com/kylelemons/godebug/pretty#Config.Compare
