### ISSUE TITLE
Compare(map,  uninitialised map) returns no output

### ISSUE THREAD

**Issue by themihai** [kylelemons/godebug#3]
var xs struct{
		x, y  map[string]string
	}
	xs.x = make(map[string]string)
	fmt.Printf("%s", pretty.Compare(xs.x, xs.y)) // returns an empty string

**Comment by kylelemons** [comment]
This is definitely the intended behavior.  If you need to inequality
between things like this or zero/nil slices, you'll need something like
reflect.DeepEqual.

**Comment by epek-test** [comment]
I see… though if Compare reports the diff between initialised and nil maps  it would improve the debug experience. I actually use reflect.DeepEqual to test the inequality and Compare to print the differences.(which I think it's how Compare is intended to be used). However if you have structs with maps there is no way to tell why the inequality fails without to reflect.DeepEqual on each map field.  Let me know if there is something I'm missing. 
  Here is an example:

	s := Some{}
	s.one = make(map[string]string)
	s1 := Some{}
	if !reflect.DeepEqual(s, s1) {
		fmt.Printf("s %v, s1 %v", s, s1)
	}

Prints 

	s {map[] map[]}, s1 {map[] map[]}

**Comment by themihai** [comment]
I see… though if Compare reports the diff between initialised and nil maps  it would improve the debug experience. I actually use reflect.DeepEqual to test the inequality and Compare to print the differences.(which I think it's how Compare is intended to be used). However if you have structs with maps there is no way to tell why the inequality fails without to reflect.DeepEqual on each map field.  Let me know if there is something I'm missing. 
  Here is an example:

	s := Some{}
	s.one = make(map[string]string)
	s1 := Some{}
	if !reflect.DeepEqual(s, s1) {
		fmt.Printf("s %v, s1 %v", s, s1)
	}

Prints 

	s {map[] map[]}, s1 {map[] map[]}

**Comment by kylelemons** [comment]
I believe the examples show that Compare(x, y) == "" is the intended way to
check rough equality.  My intent is that semantically equivalent objects be
considered equal.  Zeroed and nil slices, for instance, should work the
same in correctly-written code.  Empty and nil maps should similarly be
indistinguishable in normal use.

**Comment by voutasaurus** [comment]
While I agree that Compare is meant to be more coarse than reflect.DeepEqual, I think a "Why is reflect.DeepEqual returning false?" mode or function would be incredibly useful.

For instance `reflect.DeepEqual` says that non nil functions are never equal, even if they have the same pointer value. `pretty.Compare` will return nothing in this case. A `pretty.DeepCompare` function would instead point out that the objects contain functions.

Similarly with other things that are not DeepEqual.

**Comment by kylelemons** [comment]
Thanks for the suggestion, but I think this feature request runs counter to the goals of godebug; I would check out [go-spew](https://github.com/davecgh/go-spew) which might have the level of detail that you want.
