### ISSUE TITLE
Comparing two pointers should not nest

### ISSUE THREAD

**Issue by vincentbernat** [kylelemons/godebug#7]
Hey!

When comparing two pointers, it seems that `pretty.Compare()` doesn't satisfy itself by the pointer values being the same. It tries to compare the content of those two pointers. Usually, this works, but sometimes, one pointer can change during iteration. I understand this may be difficult to fix as currently, both values are turned into strings, then compared as strings.

**Comment by kylelemons** [comment]
Yep, the stringification is the whole basis for the library.
Pretty.Compare compares the pretty-printed values.  It doesn't even enforce
that the two values are of the same types.  As for the other point, it
can't prevent the objects from changing out from under it, you need to do
that as the caller.
