### ISSUE TITLE
pretty doesn't respect method String() string

### ISSUE THREAD

**Issue by musiphil** [kylelemons/godebug#9]
```go
type Int int

func (r Int) String() string {
	return fmt.Sprintf("Int(%d)", int(r))
}

type Box struct{ I Int }

func main() {
	i := Int(73)
	fmt.Printf("%+v\t%s\n", i, pretty.Sprint(i))

	b := Box{i}
	fmt.Printf("%+v\t%s\n", b, pretty.Sprint(b))
}
```

Expected result:
```go
Int(73)	Int(73)
{I:Int(73)}	{I: Int(73)}
```

Actual result:
```go
Int(73)	73
{I:Int(73)}	{I: 73}
```

**Comment by kylelemons** [comment]
Can you try setting `PrintStringers` in the `Config` (change `pretty.DefaultConfig` if that's your whim)?  It's not supposed to call `String()` at all unless you explicitly ask it to.

**Comment by musiphil** [comment]
Setting `PrintStringers` makes a difference indeed, but the result is a little unexpected:
```go
Int(73)	"Int(73)"
{I:Int(73)}	{I: "Int(73)"}
```
The values are printed as if they were strings from the beginning, which can be misleading: the original value is neither `73` nor `"Int(73)"`, but `Int(73)`.

Nevertheless, even if the quotes are removed in the future, having to set an option explicitly to get the `String()` method to be invoked is unintuitive and unfortunate, because the point of using this `pretty` is getting a prettier and more readable representation than what you get by a mere `fmt.Printf`, which already takes advantage of the `String()` method if available. For example, I have a `Rate` type on top of `int64` that represents the data rate in bps and that has a `String()` method that formats 40000000000 as "40 Gbps", and when a failed test prints out the diff using `pretty.Compare`, the output is very hard to read as the earlier value is not formatted as `40 Gbps` but as `40000000000`.

**Comment by kylelemons** [comment]
@musiphil I'd have to evaluate the change against the (at this point, fairly considerable) existing users (a distressing number of whom have hard-coded outputs that I'd have to update).  The reason PrintStringers is not on by default is that there are a significant number of types that have String representations for humans that don't include all of the state that a unit test cares about comparing (many structs) or which does include everything but not in a format that is amenable to diffing (e.g. protobuf), and this library was designed primarily around the pretty.Compare method for unit tests.  go-spew is a library that, I believe, was more designed around the "pretty printing for debugging," so take a look at them to see if it works better in your use case.  I have added a whitelist in 397d9a06b6442f58c63fa75896608473fe21bbb1 that you might be able to use if you want to get pretty-printing only for a few things, and it will also allow you to adjust the output to e.g. not include quotes.
